version: '3.8'

services:
  mysql:
    image: mysql:8.0.43
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3319:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-ulocal", "-plocal" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local
