logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.springframework.boot.actuate: off
    org.springframework.web: debug
    org.springframework.boot: info
    org.springframework.session: debug
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
    org.hibernate.SQL: debug
    org.hibernate.type: off
    org.hibernate.tool.schema: error
    com.zaxxer.hikari: error
    io.swagger.models.parameters.AbstractSerializableParameter: error
    io.mustelidae.otter.lutrogale: debug


server:
  error:
    include-stacktrace: always
    whitelabel:
      enabled: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 4210

spring:
  freemarker:
    check-template-location: true
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        use_sql_comments: true
        default_batch_fetch_size: 50
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect:
          storage_engine: innodb
        envers:
          revision_field_name: revision_id
          revision_type_field_name: revision_type
          store_data_at_delete: true
          global_with_modified_flag: true
          audit_strategy: org.hibernate.envers.strategy.internal.DefaultAuditStrategy
          audit_strategy_validity_end_rev_field_name: next_revision_id
          audit_strategy_validity_store_revend_timestamp: true
          audit_strategy_validity_revend_timestamp_field_name: revision_end_at
    open-in-view: true
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 3
      maximum-pool-size: 30
      pool-name: SpirngBootHikariCP
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://127.0.0.1:3319/local?serverTimezone=Asia/Seoul
    username: local
    password: local

  session:
    timeout: 30m
    jdbc:
      platform: mysql
      initialize-schema: always
  web:
    resources:
      add-mappings: false
springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    tagsSorter: alpha